export const routeNames = {
    Auth: "Auth",
    Main: "Main",
    Layout: "Layout",
    Home: "Home",
    GamePage: "GamePage",
    Profile: "Profile",
    UserGames: "UserGames",
    Login: "Login", 
    Register: "Register",
    Settings: "Settings",
    ProfileSettings: "ProfileSettings",
    EmailSettings: "EmailSettings",
    PasswordSettings: "PasswordSettings",
    UsersProfile: "UsersProfile",
    UsersGames: "UsersGames",
    ProfileGames: "ProfileGames",
    ProfileCollections: "ProfileCollections",
    ProfileCollection: "ProfileCollection"
}